Add $(top_builddir)/bin/{upcxx,upcxx-run}
This commit creates compile and run wrappers in the build directory.
These perform lazy/incremental builds of their prerequisites.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -438,6 +438,43 @@ include \$(upcxx_src)/bld/Makefile.rules
 EOF
 
 #
+# Generate top-level bin/
+#
+mkdir -p bin
+cat >| bin/upcxx <<EOF
+#!/bin/bash
+function die { echo "ERROR: \$*" >&2; exit 1; }
+vars=\$(env UPCXX_META=BUILDDIR $UPCXX_SRC/utils/upcxx.sh "\$@")
+[[ \$? -ne 0 ]] && die 'pre-parse of command line failed'
+vars=\${vars/UPCXX_NETWORK/GASNET_CONDUIT}
+vars=\${vars/UPCXX_THREADMODE=/UPCXX_BACKEND=gasnet_}
+vars=\${vars/UPCXX_CODEMODE=O3/ASSERT=0 OPTLVL=3 DBGSYM=0}
+vars=\${vars/UPCXX_CODEMODE=debug/ASSERT=1 OPTLVL=0 DBGSYM=1}
+echo 'INFO: may need to build the required runtime.  Please be patient.'
+cmd=\$($GMAKE -s -f '$PWD/Makefile' upcxx \$vars 2> /dev/null)
+[[ \$? -ne 0 ]] && die 'build of the required runtime failed.'
+exec \$cmd "\$@"
+EOF
+cat >| bin/upcxx-run <<EOF
+#!/bin/bash
+function die { echo "ERROR: \$*" >&2; exit 1; }
+conduit=\$($UPCXX_SRC/utils/upcxx-run -info "\$@" | grep ^GASNetConduitName: | cut -d' ' -f2 | tr '[A-Z]' '[a-z]')
+[[ \$? -ne 0 ]] && die 'pre-parse of command line failed'
+if [[ -d '$PWD/bld/gasnet.debug' ]]; then
+  codemode=debug
+elif [[ -d '$PWD/gasnet.opt' ]]; then
+  codemode=opt
+else
+  codemode=debug
+fi
+echo 'INFO: may need to build the required runtime.  Please be patient.'
+cmd=\$($GMAKE -s -f '$PWD/Makefile' upcxx-run GASNET_CODEMODE=\$codemode GASNET_CONDUIT=\$conduit upcxx-run 2>/dev/null)
+[[ \$? -ne 0 ]] && die 'build of the required GASNet runtime failed.'
+exec \$cmd "\$@"
+EOF
+chmod a+rx bin/upcxx bin/upcxx-run
+
+#
 # Remove any (potentially out-of-date) GASNet builds to ensure they are reconfigured
 #
 rm -Rf bld/gasnet.{opt,debug}/
