Error output on tool's failure to build runtime
This commit ensures that a failure to build a required runtime by the
in-build-tree tools `bin/upcxx{,-meta,-run}`) will present the error
output along with their own fatal error.  Additionally, these tools
now prefix their fatal error message with the tool name.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -628,7 +628,7 @@ EOF
 mkdir -p bin
 cat >| bin/upcxx <<EOF
 #!/bin/bash
-function die { echo "ERROR: \$*" >&2; exit 1; }
+function die { echo "upcxx: ERROR: \$*" >&2; exit 1; }
 vars=\$(env UPCXX_META=BUILDDIR $UPCXX_SRC/utils/upcxx.sh "\$@")
 [[ \$? -ne 0 ]] && die 'pre-parse of command line failed'
 vars=\${vars/UPCXX_NETWORK/GASNET_CONDUIT}
@@ -636,27 +636,28 @@ vars=\${vars/UPCXX_THREADMODE=/UPCXX_BACKEND=gasnet_}
 vars=\${vars/UPCXX_CODEMODE=O3/ASSERT=0 OPTLVL=3 DBGSYM=0}
 vars=\${vars/UPCXX_CODEMODE=debug/ASSERT=1 OPTLVL=0 DBGSYM=1}
 [[ -z "\$UPCXX_QUIET" ]] && echo 'INFO: may need to build the required runtime.  Please be patient.' >&2
-cmd=\$($GMAKE -s -f '$PWD/Makefile' upcxx \$vars 2> /dev/null)
-[[ \$? -ne 0 ]] && die 'build of the required runtime failed.'
-exec \$cmd "\$@"
+tmp=\$($GMAKE -f '$PWD/Makefile' upcxx \$vars 2>&1)
+[[ \$? -ne 0 ]] && echo "\$tmp" >&2 && die 'build of the required runtime failed.'
+exec \${tmp##*\$'\n'} "\$@"
 EOF
 cat >| bin/upcxx-run <<EOF
 #!/bin/bash
-function die { echo "ERROR: \$*" >&2; exit 1; }
+function die { echo "upcxx-run: ERROR: \$*" >&2; exit 1; }
 conduit=\$($UPCXX_SRC/utils/upcxx-run -info "\$@" | grep ^GASNetConduitName: | cut -d' ' -f2 | tr '[A-Z]' '[a-z]')
 [[ \$? -ne 0 ]] && die 'pre-parse of command line failed'
 codemode="${UPCXX_OPTDBG#* }" # debug unless only opt configured in
 [[ -z "\$UPCXX_QUIET" ]] && echo 'INFO: may need to build the required runtime.  Please be patient.' >&2
-cmd=\$($GMAKE -s -f '$PWD/Makefile' upcxx-run GASNET_CODEMODE=\$codemode GASNET_CONDUIT=\$conduit 2>/dev/null)
-[[ \$? -ne 0 ]] && die 'build of the required GASNet runtime failed.'
-exec \$cmd "\$@"
+tmp=\$($GMAKE -f '$PWD/Makefile' upcxx-run GASNET_CODEMODE=\$codemode GASNET_CONDUIT=\$conduit 2>&1)
+[[ \$? -ne 0 ]] && echo "\$tmp" >&2 && die 'build of the required runtime failed.'
+exec \${tmp##*\$'\n'} "\$@"
 EOF
 cat >| bin/upcxx-meta <<EOF
 #!/bin/bash
-function die { echo "ERROR: \$*" >&2; exit 1; }
+function die { echo "upcxx-meta: ERROR: \$*" >&2; exit 1; }
 [[ -z "\$UPCXX_QUIET" ]] && echo 'INFO: may need to build the required runtime.  Please be patient.' >&2
-meta=\$($GMAKE -s -f '$PWD/Makefile' upcxx-meta 2>/dev/null)
-[[ \$? -ne 0 ]] && die 'build of the required runtime failed.'
+tmp=\$($GMAKE -f '$PWD/Makefile' upcxx-meta 2>&1)
+[[ \$? -ne 0 ]] && echo "\$tmp" >&2 && die 'build of the required runtime failed.'
+meta=\${tmp##*\$'\n'}
 if [[ "\$1" == "SET" ]] ; then
   source "\$meta" ""
 elif [[ "\$1" == "DUMP" ]] ; then
