configure: update nvcc probe
This commit updates the probe for `--with-nvcc` to use the new
`check_tool_path()` function.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -644,9 +644,13 @@ fi
 if [[ $UPCXX_CUDA -eq 1 ]]; then
   trap - ERR # suspend error handler
   # UPCXX_CUDA_NVCC: the nvcc utility
-  nvcc=${UPCXX_CUDA_NVCC:-$(type -p nvcc)}
-  if [[ -z "$nvcc" ]]; then
-    echo_and_die '$UPCXX_CUDA_NVCC unset and 'nvcc' not found in $PATH'
+  nvcc=$(check_tool_path ${UPCXX_CUDA_NVCC:-nvcc})
+  if [[ $? -ne 0 ]]; then
+    if [[ -z "$UPCXX_CUDA_NVCC" ]]; then
+      echo_and_die 'ERROR: $UPCXX_CUDA_NVCC unset and 'nvcc' not found in $PATH'
+    else
+      echo_and_die "ERROR: --with-nvcc='$UPCXX_CUDA_NVCC' $nvcc"
+    fi
   fi
   echo "${nvcc}:"
   $nvcc --version
