Fix issue #33: install warning on modern g++
Expand the g++ --version parsing to be more permissive and accept
the output syntax used in some distributions.

Also add a final output message when installation fails to direct
and improve the quality of bug reports.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -68,9 +68,12 @@ if test -z "$UPCXX_INSTALL_NOCHECK" ; then (
     COMPILER_BAD=1
   elif echo "$CXXVERS" | egrep 'Apple LLVM version ([8-9]\.|[1-9][0-9])' 2>&1 > /dev/null ; then
     COMPILER_GOOD=1
-  elif echo "$CXXVERS" | egrep 'g\+\+ .GCC. [1-4]\.' 2>&1 > /dev/null ; then
+  elif echo "$CXXVERS" | egrep ' +\([^\)]+\) +[1-4]\.' 2>&1 > /dev/null ; then
     COMPILER_BAD=1
-  elif echo "$CXXVERS" | egrep 'g\+\+ .GCC. ([5-9]\.|[1-9][0-9])' 2>&1 > /dev/null ; then
+  elif echo "$CXXVERS" | egrep ' +\([^\)]+\) +([5-9]\.|[1-9][0-9])' 2>&1 > /dev/null ; then
+    # Ex: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
+    #     g++-7 (Homebrew GCC 7.2.0) 7.2.0
+    #     foo (GCC) 7.2.0
     COMPILER_GOOD=1
   elif echo "$CXXVERS" | egrep 'clang version (2|3\.[1-6])' 2>&1 > /dev/null ; then
     COMPILER_BAD=1
@@ -92,4 +95,5 @@ if test -z "$UPCXX_INSTALL_NOCHECK" ; then (
   exit 0
 ) || exit 1 ; fi
 
-nobs install src/upcxx.cpp $INSTALL_DIR
+nobs install src/upcxx.cpp $INSTALL_DIR || \
+  ( echo "UPCXX Installation failed. Please report the entire log above to: upcxx@googlegroups.com" ; exit 1; )
