Fixed issue 69: `nobs run` leverages universal spawner. `run-tests` updated accordingly.

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-export GASNET_BACKTRACE=1
-
 if [ "$1" == "-h" ]; then
     echo "Usage: RANKS=<ranks> CONDUIT=<smp|udp> ./run-tests"
     echo "  Defaults to the number of available hardware threads for RANKS, and the udp CONDUIT"
@@ -9,7 +7,7 @@ if [ "$1" == "-h" ]; then
 fi
     
 . sourceme
-rm -rf .nobs
+#rm -rf .nobs
 
 . utils/system-checks.sh
 sys_info
@@ -27,20 +25,17 @@ elif [ "$CONDUIT" != "udp" ] && [ "$CONDUIT" != "smp" ]; then
 fi
 echo "Using $CONDUIT conduit (set environment variable CONDUIT=<smp|udp> to change)"
 
-echo "Setting up upcxx... (this may take a while)"
-
 export GASNET_CONDUIT=$CONDUIT
-export GASNET_INSTALL_TO=.nobs/gasnet_conduit
-
-# always install the debug version for the test
-nobs install src/upcxx.cpp ${GASNET_INSTALL_TO}/upcxx.debug.gasnet1_seq.${GASNET_CONDUIT} &> .run-tests.err
+export GASNET_BACKTRACE=1 
+echo "Setting up upcxx... (this may take a while)"
+nobs exe test/atomics.cpp > /dev/null 2> .run-tests.err
 
 if [ $? -ne 0 ]; then
-		echo "Set up failed, here is the trace:"
-		cat .run-tests.err
+    echo "Set up failed, here is the trace:"
+    cat .run-tests.err
     rm .run-tests.err
     rm -rf .nobs
-		exit 0
+    exit 0
 fi
 rm .run-tests.err
 
@@ -48,29 +43,14 @@ cd test
 
 # Run on all available cores by default - this works on Mac and Linux
 if [ -z "$RANKS" ]; then
-    RANKS=`getconf _NPROCESSORS_ONLN`
+    export RANKS=`getconf _NPROCESSORS_ONLN`
     echo "Detected $RANKS hardware threads (set environment variable RANKS=<ranks> to change)"
 fi
-export GASNET_PSHM_NODES=${RANKS}
 
 run_test() {
 		echo "Running test $1"
-    if [ "$2" == "nopar" ]; then
-        export GASNET_PSHM_NODES=1
-        export GASNET_CONDUIT=smp
-    else
-        export GASNET_PSHM_NODES=$RANKS
-        export GASNET_CONDUIT=$CONDUIT
-    fi
-    if [ "$GASNET_CONDUIT" == "udp" ] && [ "GASNET_PSHM_NODES" != "1" ]; then
-        NOBS_EXE=$(nobs exe $1 2> .run-tests.err)
-        ${GASNET_INSTALL_TO}/bin/amudprun -np ${GASNET_PSHM_NODES} -spawn L $NOBS_EXE > .run-tests.out 2>> .run-tests.err
-    else
-        # assumes smp conduit
-		    nobs run $1 > .run-tests.out 2> .run-tests.err
-    fi
-    
-		err=$?
+    nobs run "$1" > .run-tests.out 2> .run-tests.err
+    err=$?
 		grep "Test result: " .run-tests.out
 		if [ $err -ne 0 ]; then
 				echo -e "\e[91mTest failed, here is the trace:\e[0m"
@@ -83,18 +63,18 @@ run_test() {
 
 echo "Running tests on $RANKS ranks..."
 
-run_test "atomics.cpp" "par"
-run_test "collectives.cpp" "par"
-run_test "dist_object.cpp" "par"
-run_test "future.cpp" "nopar"
-run_test "lpc_barrier.cpp" "nopar"
-run_test "rpc_barrier.cpp" "par"
-run_test "rpc_ff_ring.cpp" "par"
+run_test "atomics.cpp"
+run_test "collectives.cpp"
+run_test "dist_object.cpp"
+run_test "future.cpp"
+run_test "lpc_barrier.cpp"
+run_test "rpc_barrier.cpp"
+run_test "rpc_ff_ring.cpp"
 run_test "rput.cpp" "par"
-run_test "uts/uts_ranks.cpp" "par"
-run_test "uts/uts_threads.cpp" "nopar"
+run_test "uts/uts_ranks.cpp"
+THREADS="$RANKS" run_test "uts/uts_threads.cpp"
 
-UPCXX_BACKEND=gasnetex_par run_test "uts/uts_hybrid.cpp" "par"
+UPCXX_BACKEND=gasnetex_par run_test "uts/uts_hybrid.cpp"
 
 echo -e "\e[92mAll tests succeded\e[0m"
 
