Add timeout wrapper to run-tests, when available
This helps ensure that runaway tests don't cause run-tests targets
to hang forever, especially in CI.

The new support uses the `timeout` command (part of GNU coreutils and
commonly available by default on Linux), and is enabled by default
when the timeout command appears to be available and working.

Add exitcode to run-test failure output, and include ERROR lines
in the output file grep.

diff --git a/bld/Makefile.tests b/bld/Makefile.tests
--- a/bld/Makefile.tests
+++ b/bld/Makefile.tests
@@ -293,9 +293,20 @@ tests-clean: force
 
 .PHONY: do-tests test_install tests tests-clean
 
+TIMEOUT ?= timeout
+TIMEOUT_WRAPPER=$(TIMEOUT) --foreground -k 7m 5m
+RUN_WRAPPER=# default is to use $(TIMEOUT_WRAPPER), when available
+
 do-run-tests: force
 	@mkdir -p "$(TEST_OUTPUT)" ;                                    \
 	 if [[ -z "$(RANKS)" ]]; then ranks=4; else ranks=$(RANKS); fi; \
+	 run_wrapper='$(RUN_WRAPPER)' ;                                 \
+	 if [[ -z "$$run_wrapper" ]]; then                              \
+	   run_wrapper='$(TIMEOUT_WRAPPER)' ;                           \
+	   if [[ "`$$run_wrapper echo OK 2>&1`" != "OK" || $$? != 0 ]]; then \
+	     run_wrapper= ;                                             \
+	   fi;                                                          \
+	 fi;                                                            \
 	 total=0; failed=0;                                             \
 	 echo "Running tests with RANKS=$$ranks";                       \
 	 for test in $(call ALL_TESTS,$(NETWORKS)); do                  \
@@ -317,14 +328,15 @@ do-run-tests: force
 	     runcmd=$${!runvar};                                        \
 	   fi;                                                          \
 	   output=$(TEST_OUTPUT)/$$test-run.out ;                       \
-	   $$runcmd -np $$ranks ./$$test &> $$output;                   \
-	   if [[ $$? != 0 ]] || grep -q ERROR $$output; then            \
-	     echo FAILED; : $$((++failed));                             \
+	   $$runcmd -np $$ranks $$run_wrapper ./$$test &> $$output;     \
+	   exitcode=$$?;                                                \
+	   if [[ $$exitcode != 0 ]] || grep -q ERROR $$output; then     \
+	     echo "FAILED (exitcode=$$exitcode)"; : $$((++failed));     \
 	     $$MAKE $(MAKE_HERE) do-test-xml RESULT=run-fail OUTPUT=$$output ; \
 	   else                                                         \
 	     $$MAKE $(MAKE_HERE) do-test-xml RESULT=run-pass OUTPUT=$$output ; \
 	   fi;                                                          \
-	   grep -i -e "Test result: " -e SUCCESS $$output | sort -u;    \
+	   grep -i -e "Test result: " -e SUCCESS $$output -e ERROR | sort -u; \
 	 done;                                                          \
 	 echo -e "\nResult reports: $(TEST_OUTPUT)";                    \
 	 if [[ $$failed = 0 ]]; then                                    \
