Improve `exe` and `run` targets
If `$(SRC)` is not an absolute path and is not found as a relative
path, then we now search `test/` and `example/` in the source
directory.  The search is such that both `SRC=regression/issue219.cpp`
and `SRC=issue219.cpp` will work (and the existing logic was already
such that they hash to the same cached executable).

Also now provide a clear error if $(SRC) not found at all.

diff --git a/bld/Makefile.rules b/bld/Makefile.rules
--- a/bld/Makefile.rules
+++ b/bld/Makefile.rules
@@ -45,13 +45,26 @@ distclean: force
 	@$(MAKE) -C $(BLDDIR) $@
 	@$(MAKE) $@-hook
 
+EXE_VPATH = "$(upcxx_src)/test" "$(upcxx_src)/example"
 exe run: force
 	@if test -z "$(SRC)"; then \
-	    echo "ERROR: target '$@' requires a SRC'" >&2; \
+	    echo "ERROR: target '$@' requires a SRC" >&2; \
 	    echo "example: 'make $@ SRC=test/hello_upcxx.cpp'" >&2; \
 	    exit 1; \
 	 fi
-	@$(MAKE) -C $(BLDDIR) $@ STARTDIR="$(shell pwd)"
+	@src=$(SRC);                                                   \
+	 if [[ ! -f "$(SRC)" && "$(SRC)" != /* ]]; then                \
+	   for d in $$(find $(EXE_VPATH) -type d); do                  \
+	     if [[ -f "$$d/$(SRC)" ]]; then                            \
+	       src="$$d/$(SRC)"; break;                                \
+	     fi                                                        \
+	   done;                                                       \
+	   if [[ -z "$$src" ]]; then                                   \
+	    echo "ERROR: file SRC='$(SRC)' does not exist" >&2;        \
+	    exit 1;                                                    \
+	   fi                                                          \
+	 fi;                                                           \
+	 $(MAKE) -C $(BLDDIR) $@ SRC="$$src" STARTDIR="$(shell pwd)"
 
 # Default is pass-through
 # TODO?: HOOK and LOCAL "magic" like UPCR's multiconf
