Provide support instructions when 'all', 'check' or 'install' targets fail

diff --git a/bld/Makefile.rules b/bld/Makefile.rules
--- a/bld/Makefile.rules
+++ b/bld/Makefile.rules
@@ -34,8 +34,11 @@ install-hook: force
 	 install_to="$(prefix)" install_common
 
 install: force
-	@$(MAKE) -C $(BLDDIR) $@
-	@$(MAKE) $@-hook
+	@$(MAKE) -C $(BLDDIR) $@ || $(MAKE) failure TARGET=installation
+	@$(MAKE) $@-hook || $(MAKE) failure TARGET=installation
+
+all: force
+	@$(MAKE) -C $(BLDDIR) $@ || $(MAKE) failure TARGET=build
 
 distclean-hook: force
 	-[[ $(upcxx_src) = $(upcxx_bld) ]] || rm -R $(BLDDIR)/Makefile
@@ -70,7 +73,11 @@ exe run: force
 # TODO?: HOOK and LOCAL "magic" like UPCR's multiconf
 %: force; @$(MAKE) -C $(BLDDIR) $@
 
-.PHONY: force echovar
+failure: force
+	@echo -e '\n********\nUPC++ $(TARGET) failed. Please report the ENTIRE log above to: upcxx@googlegroups.com\n********\n' >&2
+	@exit 1
+
+.PHONY: force echovar failure
 .PHONY: install install-hook
 .PHONY: distclean distclean-hook
 .PHONY: exe run
@@ -119,5 +126,6 @@ check: force
 	   echo "PASSED $$run tests";                             \
 	 else                                                     \
 	   echo "FAILED $$failed of $$run tests";                 \
+	   $(MAKE) failure TARGET=check;                          \
 	 fi;                                                      \
 	 [[ $$failed = 0 ]] # exit code
